### PR TITLE
Restructure top navigation

### PR DESCRIPTION
**Pull request by harshjv**
Redesigned top navigation bar.

Screenshots:

image

image

### CODE REVIEW

**Comment by mzagaja** [comment]
After merging #34 I see there are merge conflicts. Would you mind fixing the merge conflicts (I cannot do it locally since it's from your fork) and then I'll merge this in. I'm then going to do #37 and then #39. Those might have merge conflicts after I merge this one.

**Comment by harshjv** [comment]
Okay, Matt, I'll resolve those conflicts.




Keybase: https://keybase.io/harshjv
<https://mailtrack.io/trace/link/4c4df52b272e9944d3edf41d3d4e51c9b64f1891?url=https%3A%2F%2Fkeybase.io%2Fharshjv&signature=1ce1a9468ddfafa9>
PGP Key: https://harshjv.github.io/pgp-key
<https://mailtrack.io/trace/link/581861a43ebbf9c757a1bf7ca4c58809ae2b95a9?url=https%3A%2F%2Fharshjv.github.io%2Fpgp-key&signature=ce30649463bf2854>
LinkedIn: https://www.linkedin.com/in/harshjv
<https://mailtrack.io/trace/link/3039b980d718665bf29e029a657348ebc6f3af24?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fharshjv&signature=30a632ef23475a21>
GitHub: https://github.com/harshjv
<https://mailtrack.io/trace/link/cfe84461b057b49c48e5a07e2fac2574fac9b4ad?url=https%3A%2F%2Fgithub.com%2Fharshjv&signature=61965f9098cd9b92>
Twitter: https://twitter.com/harshjv
<https://mailtrack.io/trace/link/0de6e0dfbafbcc994d26b8f25f685ca79b677c49?url=https%3A%2F%2Ftwitter.com%2Fharshjv&signature=9656a45a38020f0e>
Blog: https://harshjv.github.io
<https://mailtrack.io/trace/link/f989d106c8b0ae4a1f5e9e6e5a1ecdb6d30bfa78?url=https%3A%2F%2Fharshjv.github.io&signature=eec172689a81f052>

**Comment by mzagaja** [comment]
Hi @harshjv just wanted to see if you've made any progress on this? Hoping to try and merge the rest of this in this week.

**Comment by harshjv** [comment]
@mzagaja hey, as per the discussion, you wanted me to not to change the top navigation bar, so let's not merge this PR at all. I am working on other PRs to solve merge conflicts.

**Pull request closed without merging**
